version: "3.9"
services:
  etf_trend_monitor:
    build: .
    container_name: etf_trend_monitor
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env:ro
      - ./etf-list.csv:/app/etf-list.csv
      - ./cache_prices:/app/cache_prices
    restart: unless-stopped
    tty: true
