version: "3.9"
services:
  etf_trend_monitor:
    build: .
    container_name: etf_trend_monitor
    image: ghcr.io/mosesmc52/etf-trend-monitor:${TAG:-latest}
    restart: unless-stopped
    tty: true
